# SPDX-FileCopyrightText: Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Additional dependencies needed by a some of the Morpheus examples.
# The intended usage is to first create the conda environment from the `cuda11.8_dev.yml` file, and then update the
# env with this file. ex:
#   mamba env create -n  morpheus --file docker/conda/environments/cuda11.8_dev.yml
#   conda activate morpheus
#   mamba env update -n morpheus --file docker/conda/environments/cuda11.8_examples.yml
channels:
    - rapidsai
    - nvidia
    - huggingface
    - conda-forge
    - dglteam/label/cu118
dependencies:
    - arxiv=1.4
    - boto3
    - cuml=23.06
    - dask>=2023.1.1
    - dgl=1.0.2
    - dill=0.3.6
    - distributed>=2023.1.1
    - langchain=0.0.190
    - libwebp>=1.3.2 # Required for CVE mitigation: https://nvd.nist.gov/vuln/detail/CVE-2023-4863
    - mlflow>=2.2.1,<3
    - newspaper3k=0.2
    - papermill=2.3.4
    - pypdf=3.16
    - requests-cache=1.1
    - s3fs>=2023.6
    - sentence-transformers
    - transformers

    ####### Pip Transitive Dependencies (keep sorted!) #######
    # These are dependencies that are available on conda, but are required by the pip packages listed below. Its much
    # better to install them with conda than pip to allow for better dependency resolution.
    - environs=9.5
    - minio=7.1
    - python-dotenv=1.0
    - ujson=5.8


  ####### Pip Dependencies (keep sorted!) #######
    - pip:
        - grpcio-status==1.58 # To keep in sync with 1.58 grpcio which is installed for Morpheus
        - nemollm
