# SPDX-FileCopyrightText: Copyright (c) 2021-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: morpheus
channels:
    - rapidsai
    - nvidia
    - nvidia/label/dev # For pre-releases of SRF. Should still default to full releases if available
    - conda-forge
dependencies:
    ####### Morpheus Dependencies (keep sorted!) #######
    - automake=1.16.5
    - benchmark=1.6.1
    - boost-cpp=1.74
    - cachetools=5.0.0
    - ccache>=3.7
    - clangdev=14
    - click >=8
    - cmake=3.22
    - configargparse=1.5
    - cuda-nvml-dev=11.7
    - cuda-python<=11.7.0 # Remove when Issue #251 is closed
    - cudatoolkit=11.7
    - cudf 22.08
    - cudf_kafka 22.08.*
    - cupy=9.5.0
    - cython=0.29.24
    - datacompy=0.8
    - docker-compose=1.29.2
    - docker-py=5.0
    - faker=12.3.0
    - flake8
    - flatbuffers=2.0
    - gcc_linux-64=9.4
    - gflags=2.2
    - git>=2.35.3 # Needed for wildcards on safe.directory
    - git-lfs=3.2
    - glog=0.6
    - gmock=1.10
    - gputil
    - grpc-cpp>=1.43
    - grpcio
    - gtest=1.10
    - gxx_linux-64=9.4
    - include-what-you-use=0.18
    - isort
    - librdkafka=1.7.0
    - mlflow>1.29,<2
    - myst-parser==0.17
    - networkx=2.8
    - ninja=1.10
    - nodejs=17.4.0
    - numba==0.55
    - numpydoc=1.4
    - pandas=1.3
    - pip
    - pkg-config # for srf cmake
    - pluggy=1.0
    - protobuf=3.20
    - pybind11-stubgen=0.10.5
    - pydot
    - pytest
    - pytest-benchmark>=4.0
    - pytest-cov
    - python-confluent-kafka=1.7.0
    - python-graphviz
    - python=3.8
    - rapidjson=1.1.0
    - scikit-build=0.13
    - sphinx
    - sphinx_rtd_theme
    - srf 22.11.*
    - sysroot_linux-64=2.17
    - tqdm=4
    - typing_utils=0.1
    - watchdog=2.1
    - yapf=0.32.0
    ####### Morpheus Pip Dependencies (keep sorted!) #######
    - pip:
        # Add additional dev dependencies here
        - docutils
        # Ensure all runtime requirements are installed using the requirements file
        - --requirement requirements.txt
