 name: JulieOps
  # You may pin to the exact commit or the version.
  # uses: kafka-ops/julieops-github-action@ea25f12c0be4466271eb93f9bef7c0fd206190a1
  uses: kafka-ops/julieops-github-action@v1
  with:
    # A list of brokers where this agent is going to connect
    brokers: # default is 
    # The location for your topology file
    topology: # default is /opt/julieops/topology.yml
    # The config file used by JulieOps
    config: # default is /opt/julieops/config.properties
