- name: Setup Kafka
  # You may pin to the exact commit or the version.
  # uses: 280780363/kafka-action@a66f129ffd34e42d6245b7e25d69e94659a1d444
  uses: 280780363/kafka-action@v1.0
  with:
    # Version of Bitnami Kafka to use
    kafka version: # optional, default is latest
    # Version of Bitnami Zookeeper to use
    zookeeper version: # optional, default is latest
    # The port of Kafka host
    kafka port: # optional, default is 9092
    # The port of Zookeeper host
    zookeeper port: # optional, default is 2181
    # Configure of auto.create.topics.enable
    auto create topic: # optional, default is true
