name: Build pull request

on:
  push:
    branches:
      - 'pull-request/**'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  # AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  # AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  CUDA_VER: "11.5"
  MORPHEUS_ROOT: "${{ github.workspace }}/morpheus"
  PYTHON_VER: "3.8"
  RAPIDS_VER: "22.06"
  WORKSPACE: "${{ github.workspace }}/morpheus"
  WORKSPACE_TMP: "${{ github.workspace }}/tmp"
  USE_SCCACHE: "1"
  GIT_COMMIT: "${{ github.sha }}"
  PATH: "/opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/gcc9/bin:/usr/local/binutils/bin:/usr/lib64/openmpi/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

jobs:
  check:
    name: Check
    runs-on: [self-hosted, linux, amd64, cpu4]
    timeout-minutes: 60
    container:
      image: gpuci/rapidsai-driver:22.04-cuda11.5-devel-centos7-py3.8
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: false
          path: 'morpheus'
          fetch-depth: '0'

      - name: Check
        shell: bash
        run: ./morpheus/ci/scripts/github/checks.sh
