 name: Install Vulkan SDK
  # You may pin to the exact commit or the version.
  # uses: humbletim/install-vulkan-sdk@6aadcb709dbb8e4096dad20e35adaefec83d4b45
  uses: humbletim/install-vulkan-sdk@v1.1.1
  with:
    # official Vulkan SDK release version to use
    version: # default is latest
    # whether to cache the downloaded vulkan_sdk.* installer file (using github actions/cache)
    cache: # optional
    # silence GitHub Annotation notice displayed if resolving `latest` into Vulkan SDK release number
    quiet: # optional
